[tools]
"aqua:pulumi/pulumi" = "latest"
"cargo:bob-nvim" = "latest"
"cargo:cargo-watch" = "latest"
"cargo:difftastic" = "latest"
"cargo:hurl" = "latest"
"cargo:just" = "latest"
"cargo:mdbook" = "latest"
"cargo:mprocs" = "latest"
"cargo:sshx" = "latest"
"cargo:starship" = "latest"
"cargo:stylua" = "latest"
"cargo:tree-sitter-cli" = "latest"
"cargo:typstyle" = "latest"
"cargo:watchexec-cli" = "latest"
"cargo:zellij" = "latest"
"github:Kampfkarren/selene" = "latest"
"github:alexpasmantier/television" = { version = "latest", exe = "tv" }
"github:ast-grep/ast-grep" = "latest"
"github:block/goose" = "latest"
"github:charmbracelet/crush" = "latest"
"github:dagger/container-use" = "latest"
"github:docker/docker-credential-helpers" = { version = "latest", exe = "docker-credential-secretservice" }
"github:elixir-lang/expert" = { version = "nightly", version_prefix = "" }
"github:exercism/cli" = { version = "latest", exe = "exercism" }
"github:git-bug/git-bug" = "latest"
"github:git-ecosystem/git-credential-manager" = { version = "latest", extract_all = "true", matching_regex = "\\d+\\.tar.gz" }
"github:git-lfs/git-lfs" = "latest"
"github:google/yamlfmt" = "latest"
"github:jesseduffield/lazydocker" = "latest"
"github:jesseduffield/lazygit" = "latest"
"github:k1LoW/tbls" = "latest"
"github:knqyf263/pet" = "latest"
"github:koalaman/shellcheck" = "latest"
"github:quarylabs/sqruff" = "latest"
"github:sigstore/cosign" = "latest"
"github:terrastruct/d2" = "latest"
"github:typst/typst" = "latest"
"npm:@github/copilot" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@qwen-code/qwen-code" = "latest"
"npm:@withgraphite/graphite-cli" = "stable"
"npm:heroku" = "latest"
"npm:markdownlint-cli" = "latest"
"npm:oxlint" = "latest"
"npm:prettier" = "latest"
"npm:surge" = "latest"
"pipx:ansible" = { version = "latest", uvx_args = "--with-executables-from ansible-core,ansible-lint" }
"pipx:ansible-lint" = "latest"
"pipx:djlint" = "latest"
"pipx:grip" = "latest"
"pipx:litecli" = "latest"
"pipx:poetry" = "latest"
"pipx:sqlite-utils" = "latest"
"pipx:yamllint" = "latest"
# "github:TibixDev/winboat" = { version = "latest", extract_all = "true", matching_regex = "\\d+\\.tar.gz" }
# "github:cloudflare/cloudflared" = "latest"
# "github:hovancik/stretchly" = { version = "latest", extract_all = "true", matching_regex = "tar.xz$" }
# "pipx:harlequin" = "latest"
# "pipx:mitmproxy" = "latest"
# "pipx:virtualenv" = "latest"
bun = "latest"
cargo-binstall = "latest"
deno = "latest"
elixir = "latest"
erlang = "latest"
java = "17"
node = "latest"
prek = "latest"
ruby = "3.4.7"
uv = "latest"

[settings]
asdf = false
auto_install = false
experimental = true
http_timeout = "600s"
idiomatic_version_file_enable_tools = ["ruby", "python", "node", "go"]
paranoid = true
pipx_uvx = true
python.uv_venv_auto = true
vfox = false
